# Cloudflare Pages Configuration
# This file is automatically detected by Cloudflare Pages

# Build settings
production_branch = "main"
build_command = "npm run build"
build_output_directory = "dist"

# Environment variables for build (can be set in Cloudflare Pages dashboard)
# NODE_VERSION = "18"
# NPM_VERSION = "8"

# Compatibility settings
compatibility_date = "2023-12-01"
compatibility_flags = []
