name = "leoaugusto"
compatibility_date = "2023-12-01"

[env.production]
account_id = ""  # You'll need to add your Cloudflare account ID here

[[env.production.routes]]
pattern = "*"
custom_domain = true

[build]
command = "npm run build"
cwd = ""
watch_dir = ""

[build.upload]
format = "service-worker"
dir = "dist"
main = ""
rules = [
  { type = "ESModule", globs = ["**/*.js"] },
  { type = "CompiledWasm", globs = ["**/*.wasm"] },
  { type = "Text", globs = ["**/*.txt", "**/*.html"] }
]
